---
- name:
  hosts: all
  vars:
    distribution:

  tasks:
    - {include: updates.yml, become: true}
#    - {include: rootlock.yml, become: true}
#    - {include: ufw.yml, become: true}
#    - {include: cronjobs.yml, become: true}


